- name: Install Portainer
  shell: >
        docker volume create portainer_data && 
        docker run -d -p 9000:9000 -p 8000:8000 --name portainer --restart always 
        -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
  run_once: true

- name: Install Portainer Agents
  shell: >
        curl -L https://downloads.portainer.io/portainer-agent-stack.yml -o portainer-agent-stack.yml && 
        docker stack deploy --compose-file=portainer-agent-stack.yml portainer &&
        rm -f portainer-agent-stack.yml
  warn: false
  run_once: true


