- name: Create promtail directory if it does not exist
  file:
    path: /etc/promtail/
    state: directory
    mode: '777'

- name: Fix permissions for promtail mnt folder
  file:
    path: /etc/promtail/
    group: nogroup
    recurse: yes
  become: yes

- name: Deploy Templated promtail Config file
  template:
    src: promtail-docker-config.yaml
    dest: /etc/promtail/promtail-docker-config.yaml
    mode: '666'