- targets:
    - tcp://1.1.1.1:53
  labels:
    service: CloudFare
- targets:
    - tcp://youtube.com:80
  labels:
    service: YouTube
- targets:
    - tcp://prod.http1.eu-west-1.prodaa.netflix.com:443
    - tcp://ipv4-c022-lhr001-virginmedia-isp.1.oca.nflxvideo.net:443
  labels:
    service: Netflix
- targets:
    - tcp://amazon.co.uk:80
  labels:
    service: Amazon
- targets:
    - tcp://google.com:80
    - tcp://8.8.8.8:53
  labels:
    service: Google
- targets:
    - tcp://194.168.4.100:53
    - tcp://194.168.8.100:53
  labels: 
    service: Virgin
- targets:
    - tcp://microsoft.com:3479
    - tcp://microsoft.com:3480
    - tcp://microsoft.com:3481
  labels:
    service: Skype
- targets:
    - tcp://zoom.us:80
    - tcp://zoom.us:443
    - udp://zoom.us:3478
    - udp://zoom.us:3479
    - udp://zoom.us:8801
    - udp://zoom.us:8802
  labels:
    service: Zoom