---

# There is some weird issue when running Docker Swarm nodes on a RaspberryPi
# The IPv4 address seems to "disappear" every 24 hours or so. It can be restored with this command
- name: Set up nightly manual DHClient renewal
  become: yes
  cron:
    name: "Renew eth0 IPv4 address"
    hour: "0"
    job: "dhclient -r eth0 && dhclient eth0"