- name: 'Install required packages to build DUC'
  become: yes
  apt:
    pkg:
      - make
      - gcc

- name: Create a Source directory if it does not exist
  become: yes
  file:
    path: /usr/local/src
    state: directory
    mode: '0755'

- name: Download the NOIP Dynamic Update Client
  become: yes
  get_url:
    url: https://www.noip.com/client/linux/noip-duc-linux.tar.gz
    dest: /usr/local/src/noip-duc-linux.tar.gz
    checksum: md5:3b0f5f2ff8637c73ab337be403252a60
    mode: '0600'

- name: Unpack the client
  become: yes
  unarchive:
    src: /usr/local/src/noip-duc-linux.tar.gz
    dest: /usr/local/src
    remote_src: yes

- name: Build the client
  become: yes
  community.general.make:
    chdir: /usr/local/src/noip-2.1.9-1

- name: Copy the binary to /usr/local/bin
  become: yes
  copy:
    remote_src: yes
    src: /usr/local/src/noip-2.1.9-1/noip2
    dest: /usr/local/bin/noip2
    mode: 0755

- name: Create the NOIP configuration file
  become: yes
  command: "/usr/local/bin/noip2 -C -U 5 -u {{noip_username}} -p {{noip_password}} -Y -I eth0"

- name: Set up the NOIP service
  become: yes
  copy:
    src: noip2.service
    dest: /etc/systemd/system/noip2.service
    mode: 0600

- name: Start the NOIP client
  become: yes
  systemd:
    enabled: yes
    state: started
    name: noip2