server:
  http_listen_port: {{promtail.port.http}}
  grpc_listen_port: {{promtail.port.grpc}}

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:{{loki.port.http}}/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      host: {{inventory_hostname}}
      __path__: /var/host_log/*log

- job_name: nginx
  pipeline_stages:
  - json:
      expressions:
        request_uri: request_uri
        remote_addr: remote_addr
        request_method: request_method
        http_host: http_host
  - labels:
      request_uri: 
      remote_addr: 
      request_method: 
      http_host: 
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      host: {{inventory_hostname}}
      __path__: /var/host_log/nginx/*log

