{
 "title": "Network Latency",
 "time": { "from": "2021-02-09T12:39:13.799Z", "to": "2021-02-09T12:49:13.799Z" },
 "templating": {
  "list": [
   { "name": "Service", "query": "label_values(service)" }
  ]
 },
 "panels": [
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Service" },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "Round Trip {{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 89 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 96 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 103 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 111 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 118 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 125 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 133 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 140 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 147 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 155 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 162 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 169 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 177 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 184 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 191 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  },
  { "title": "$Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "TCP Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 199 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "TCP Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 206 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{service=\"$Service\",job=\"blackbox-tcp\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Round trip time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}} Jitter"
    }
   ]
  },
  {
   "title": "ICMP Round trip time History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 213 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\", service=\"$Service\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1-avg_over_time(probe_success{service=\"$Service\",job=\"blackbox-icmp\"}[$__interval])!=0 or null",
     "legendFormat": "Packet Loss {{instance}}"
    }
   ]
  }
 ]
}