{
 "title": "Energy Usage",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "NetatmoRoom",
    "label": "Netatmo Room",
    "query": "label_values(temperature_c, friendly_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Energy Bills",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    { "expr": "sensor_unit_gbp", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Energy Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    { "expr": "sensor_unit_kwh", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Switches On",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "switch_state", "legendFormat": "{{friendly_name}}" }
   ]
  },
  { "title": "$NetatmoRoom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "NetatmoRoom" },
  {
   "title": "Room Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "current_temperature_c{friendly_name=\"$NetamoRoom\"}",
     "legendFormat": "{{friendly_name}} Temperature"
    },
    {
     "expr": "temperature_c{friendly_name=\"$NetamoRoom\"}",
     "legendFormat": "{{friendly_name}} Setpoint"
    }
   ]
  }
 ]
}