{
 "title": "Windows System",
 "description": "Windows Full System Metrics",
 "tags": [
  "windows",
  "windows_exporter",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(windows_system_system_up_time, node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "repeat": "host",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_os_time{node_name=~\"$server\"} - windows_system_system_up_time{node_name=~\"$server\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", node_name=~\"$server\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{node_name=~\"$server\"} - windows_os_physical_memory_free_bytes{node_name=~\"$server\"}) / windows_cs_physical_memory_bytes{node_name=~\"$server\"} * 100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", node_name=\"$server\"}) by (instance) - sum(windows_logical_disk_free_bytes{volume!~\"Harddisk.*\", node_name=\"$server\"}) by (instance)) / sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", node_name=\"$server\"}) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{node_name=\"$server\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_cs_physical_memory_bytes{node_name=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Physical memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_physical_memory_free_bytes{node_name=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Free physical memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_virtual_memory_bytes{node_name=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Virtual memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "windows_os_virtual_memory_free_bytes{node_name=~\"$server\"}",
     "legendFormat": "Free virtual memory"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "repeat": "host",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_cs_logical_processors{node_name=~\"$server\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{node_name=~\"$server\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{node_name=~\"$server\"}[5m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU without Idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(windows_cpu_time_total{node_name=\"$server\",mode!=\"idle\"}[5m])) by (mode)) / 16)* 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU by Process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (process) (rate(windows_process_cpu_time_total{node_name=~\"$server\",process!=\"Idle\"}[5m])) > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory by Process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (process) (windows_process_private_bytes{node_name=~\"$server\",process!=\"Idle\"}) > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{process}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Handles by Process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (process) (rate(windows_process_handle_count{node_name=~\"$server\",process!=\"Idle\"}[5m])) > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "IO Bytes by Process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (process) (rate(windows_process_io_bytes_total{node_name=~\"$server\",process!=\"Idle\"}[5m])) > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "IO Ops by Process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (process) (rate(windows_process_io_operations_total{node_name=~\"$server\",process!=\"Idle\"}[5m])) > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{node_name=~\"$server\",nic!=\"Npcap_Loopback_Adapter\"}[$interval]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent Bytes",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(windows_net_bytes_received_total{node_name=~\"$server\",nic!=\"Npcap_Loopback_Adapter\"}[$interval]) <0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received Bytes",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded{node_name=~\"$server\", nic!=\"Npcap_Loopback_Adapter\"}[$interval]) + irate(windows_net_packets_outbound_errors{node_name=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent Packets",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_received_discarded{node_name=~\"$server\", nic!=\"Npcap_Loopback_Adapter\"}[$interval]) + irate(windows_net_packets_received_errors{node_name=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received Packets",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{node_name=~\"$server\", volume !~\"HarddiskVolume.+\"}[30s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- irate(windows_logical_disk_read_bytes_total{node_name=~\"$server\", volume !~\"HarddiskVolume.+\"}[30s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{node_name=~\"$server\", volume !~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "free {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hard disk i/o ops total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_split_ios_total{node_name=~\"$server\", volume !~\"HarddiskVolume.+\"}[30s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "i/o {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "windows_os_processes", "legendFormat": "Processes" }
   ]
  },
  {
   "title": "Services by state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{node_name=~\"$server\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "system_threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{node_name=~\"$server\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "system_threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System exception dispatches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_system_exception_dispatches_total{node_name=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "exceptions",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}