{
 "title": "Home Assistant",
 "description": "Docker Swarm nodes metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, sum((node_time_seconds{node_name=~\"homeassistant\"} - node_boot_time_seconds{node_name=~\"homeassistant\"})))"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\", node_name=~\"homeassistant\"}[$interval]) ) * 100 / count(node_cpu_seconds_total{mode=\"user\", node_name=~\"homeassistant\"} ) "
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{node_name=~\"homeassistant\"}",
     "legendFormat": "load5 {{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", node_name=~\"homeassistant\"}[$interval]) * 100))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(avg(node_hwmon_temp_celsius{node_name=~\"homeassistant\"}))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node_name=~\"homeassistant\"})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable_bytes{node_name=~\"homeassistant\"} / node_memory_MemTotal_bytes{node_name=~\"homeassistant\"}) * 100) "
    }
   ]
  },
  {
   "title": "Total swap memory used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((node_memory_SwapTotal_bytes{node_name=~\"homeassistant\"} - node_memory_SwapFree_bytes{node_name=~\"homeassistant\"}))"
    }
   ]
  },
  {
   "title": "Used swap memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(((node_memory_SwapTotal_bytes{node_name=~\"homeassistant\"} - node_memory_SwapFree_bytes{node_name=~\"homeassistant\"}) / node_memory_SwapTotal_bytes{node_name=~\"homeassistant\"}) * 100)"
    }
   ]
  },
  {
   "title": "Swap used / total RAM memory ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(((node_memory_SwapTotal_bytes{node_name=~\"homeassistant\"} - node_memory_SwapFree_bytes{node_name=~\"homeassistant\"}) / node_memory_MemTotal_bytes{node_name=~\"homeassistant\"}) * 100)"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/var\",node_name=~\"homeassistant\"})"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((node_filesystem_free_bytes{mountpoint=\"/var\",node_name=~\"homeassistant\"} / node_filesystem_size_bytes{mountpoint=\"/var\",node_name=~\"homeassistant\"})* 100) "
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node_name=~\"homeassistant\"} - node_memory_MemFree_bytes{node_name=~\"homeassistant\"} - node_memory_Cached_bytes{node_name=~\"homeassistant\"} - node_memory_Buffers_bytes{node_name=~\"homeassistant\"} - node_memory_Slab_bytes{node_name=~\"homeassistant\"})",
     "legendFormat": "Used {{node_name}}"
    },
    {
     "expr": "sum(node_memory_Cached{node_name=~\"homeassistant\"})",
     "legendFormat": "Cached {{node_name}}"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{node_name=~\"homeassistant\"})",
     "legendFormat": "Free {{node_name}}"
    }
   ]
  },
  {
   "title": "Swap memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{node_name=~\"homeassistant\"} - node_memory_SwapFree_bytes{node_name=~\"homeassistant\"})",
     "legendFormat": "Used {{node_name}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{node_name=~\"homeassistant\"} [$interval]))",
     "legendFormat": "Read {{node_name}}"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{node_name=~\"homeassistant\"}  [$interval]))",
     "legendFormat": "Written {{node_name}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{node_name=~\"homeassistant\"}[$interval]))",
     "legendFormat": "Reads {{node_name}}"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed_total{node_name=~\"homeassistant\"}[$interval]))",
     "legendFormat": "Writes {{node_name}}"
    }
   ]
  },
  {
   "title": "CPU IO Wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(node_cpu_seconds_total{mode=\"iowait\",node_name=~\"homeassistant\"}[$interval])* 100) )",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}