---
- name: Add Workers to the Swarm
  shell: "docker swarm join --token {{ hostvars['pinode01']['worker_token']['stdout'] }} {{ hostvars['pinode01']['ansible_default_ipv4']['address'] }}:2377"
  tags: swarm
